import AcquisitionIntelligence from "./AcquisitionIntelligence";
import AutonomousIntelligence from "./AutonomousIntelligence";
import React,{useEffect,useMemo,useState} from "react";
import {api,clearToken,getToken} from "./api";
import OutreachCenter from "./OutreachCenter";
import ProposalWorkspace from "./ProposalWorkspace";

function Login({onLogin}){
 const [username,setUsername]=useState(""),[password,setPassword]=useState(""),[error,setError]=useState(""),[loading,setLoading]=useState(false);
 async function submit(e){e.preventDefault();setLoading(true);setError("");try{await api.login(username,password);onLogin()}catch(err){setError(err.message)}finally{setLoading(false)}}
 return <div className="auth-shell"><form className="auth-card" onSubmit={submit}><div className="eyebrow">SSVPRASAD · PRIVATE WORKSPACE</div><h1>Freelance Acquisition Agent</h1><p>Sign in to access your leads, qualification pipeline and reviewable outreach.</p>{error&&<div className="error">{error}</div>}<input value={username} onChange={e=>setUsername(e.target.value)} placeholder="Username" autoComplete="username" required/><input value={password} onChange={e=>setPassword(e.target.value)} placeholder="Password" type="password" autoComplete="current-password" required/><button disabled={loading}>{loading?"Signing in…":"Sign in"}</button><button type="button" className="secondary" onClick={()=>{window.location.search="?demo=1"}}>Preview dashboard</button><small>Create the first account with Django's createsuperuser command.</small></form></div>
}

function App(){
 const demoMode=import.meta.env.VITE_PUBLIC_PREVIEW!=="false";
 const demoLeads=[{id:"demo-1",title:"AI workflow automation for SaaS operations",company:"Demo Client Co.",source:"Demo preview",lead_type:"freelance",description:"Build an AI-powered workflow automation system integrating React, Django and OpenAI.",budget_text:"$1,500–$3,000",technologies:["React","Django","OpenAI"],status:"qualified",analysis:{match_score:92,confidence:91}},{id:"demo-2",title:"Django + React dashboard modernization",company:"Example Labs",source:"Demo preview",lead_type:"freelance",description:"Modernize an existing business dashboard and add automation features.",budget_text:"$2,000–$4,000",technologies:["Django","React","PostgreSQL"],status:"new",analysis:{match_score:84,confidence:87}},{id:"demo-3",title:"AI client acquisition prototype",company:"Startup Demo",source:"Demo preview",lead_type:"freelance",description:"Prototype a lead discovery, qualification and proposal workflow.",budget_text:"$1,000–$2,500",technologies:["Python","OpenAI","APIs"],status:"proposal",analysis:{match_score:78,confidence:83}}];
 const [dashboard,setDashboard]=useState(demoMode?{opportunities:3,qualified:1,high_match:2,proposals:1,followups_due:0,last_discovery_at:null}:{}),[analytics,setAnalytics]=useState(null),[leads,setLeads]=useState(demoMode?demoLeads:[]),[qualified,setQualified]=useState([]),[followups,setFollowups]=useState([]),[dueFollowups,setDueFollowups]=useState([]);
 const [followupDate,setFollowupDate]=useState(""),[followupMessage,setFollowupMessage]=useState(""),[replyMessage,setReplyMessage]=useState("");
 const [sort,setSort]=useState("score"),[leadPage,setLeadPage]=useState(1),[leadPagination,setLeadPagination]=useState({}),[selected,setSelected]=useState(null),[analysis,setAnalysis]=useState(null),[proposal,setProposal]=useState(null),[replyClassification,setReplyClassification]=useState(null),[proposalWorkspaceId,setProposalWorkspaceId]=useState(null),[sequence,setSequence]=useState(null);
 const [loading,setLoading]=useState(false),[error,setError]=useState(""),[filter,setFilter]=useState("all"),[query,setQuery]=useState("AI automation Django React freelance"),[discoveryResult,setDiscoveryResult]=useState(null),[loggedIn,setLoggedIn]=useState(demoMode||Boolean(getToken())),[worker,setWorker]=useState(null);
 async function refresh(){if(demoMode)return;const base=(import.meta.env.VITE_API_BASE_URL||"http://127.0.0.1:8000/api").replace(/\/$/,"");const [d,a,l,q,f,df,h]=await Promise.all([api.dashboard(),api.analytics(),api.leads(leadPage),api.qualified(),api.followups(),api.dueFollowups(),fetch(base+"/health/").then(r=>r.json())]);setDashboard(d);setAnalytics(a);setLeads(l.results||[]);setLeadPagination(l);setQualified(q);setFollowups(f);setDueFollowups(df);setWorker(h.workers||null);if(selected)setSelected((l.results||[]).find(x=>x.id===selected.id)||selected)}
 useEffect(()=>{if(!loggedIn||demoMode)return;refresh().catch(e=>{if(!getToken())setLoggedIn(false);else setError(e.message)});const handler=()=>setLoggedIn(false);window.addEventListener("auth-expired",handler);return()=>window.removeEventListener("auth-expired",handler)},[loggedIn,leadPage]);
 async function runDiscovery(){if(demoMode){setError("Preview mode is read-only. Connect the Django backend for live discovery.");return;}setLoading(true);setError("");setDiscoveryResult(null);try{const d=await api.discover(query,"live"),q=await api.qualify(20);setDiscoveryResult({...d,...q});await refresh()}catch(e){setError(e.message)}finally{setLoading(false)}}
 const visible=useMemo(()=>{const base=filter==="fresh-qualified"?qualified:(filter==="all"?leads:leads.filter(l=>l.status===filter));return [...base].sort((a,b)=>sort==="score"?((b.analysis?.match_score||0)-(a.analysis?.match_score||0)):sort==="newest"?(new Date(b.posted_at||b.discovered_at||0)-new Date(a.posted_at||a.discovered_at||0)):(a.title||"").localeCompare(b.title||""))},[leads,qualified,filter,sort]);
 function selectLead(lead){setSelected(lead);setAnalysis(lead.analysis||null);setProposal(null);setReplyClassification(null);setSequence(null);setReplyMessage("")}
 async function runAnalysis(){if(demoMode){setError("Preview mode is read-only.");return;}if(!selected)return;setLoading(true);setError("");try{const d=await api.analyze(selected.id);setSelected(d);setAnalysis(d.analysis);await refresh()}catch(e){setError(e.message)}finally{setLoading(false)}}
 async function generateProposal(){if(demoMode){setError("Preview mode is read-only.");return;}if(!selected||!analysis)return;setLoading(true);try{setProposal(await api.proposal(selected.id));await refresh()}catch(e){setError(e.message)}finally{setLoading(false)}}
 async function approveProposal(){if(!selected||!proposal)return;setLoading(true);try{setProposal(await api.approveProposal(selected.id));await refresh()}catch(e){setError(e.message)}finally{setLoading(false)}}
 async function sendProposal(){if(!proposal?.outreach_id)return;setLoading(true);try{const result=await api.sendOutreach(proposal.outreach_id);setProposal({...proposal,...result,status:result.sent?"sent":proposal.status});await refresh()}catch(e){setError(e.message)}finally{setLoading(false)}}
 async function setStatus(status){if(!selected)return;setLoading(true);try{const d=await api.setStatus(selected.id,status);setSelected(d);setAnalysis(d.analysis||analysis);await refresh()}catch(e){setError(e.message)}finally{setLoading(false)}}
 async function createReply(){if(!selected||!replyMessage.trim())return;setLoading(true);try{const d=await api.createReply(selected.id,replyMessage.trim());setSelected({...selected,status:"replied"});setReplyClassification(d.classification||null);setReplyMessage("");await refresh()}catch(e){setError(e.message)}finally{setLoading(false)}}
 async function createFollowup(){if(!selected||!followupDate||!followupMessage.trim())return;setLoading(true);try{await api.createFollowup({lead_id:selected.id,scheduled_at:new Date(followupDate).toISOString(),message:followupMessage.trim()});setFollowupDate("");setFollowupMessage("");await refresh()}catch(e){setError(e.message)}finally{setLoading(false)}}
 async function approveFollowup(id){setLoading(true);try{await api.approveFollowup(id);await refresh()}catch(e){setError(e.message)}finally{setLoading(false)}}
 async function createSequence(){if(!selected)return;setLoading(true);try{const d=await api.createFollowupSequence(selected.id,{delays_days:[3,5,7],max_steps:3});setSequence(d.sequence);await refresh()}catch(e){setError(e.message)}finally{setLoading(false)}}
 async function sendFollowup(id){setLoading(true);try{await api.sendFollowup(id);await refresh()}catch(e){setError(e.message)}finally{setLoading(false)}}
 if(!loggedIn)return <Login onLogin={()=>setLoggedIn(true)}/>;
 return <div className="app"><header className="topbar"><div><div className="eyebrow">SSVPRASAD · LIVE V1</div><h1>AI Freelance Acquisition Agent</h1><p>Find live opportunities, qualify fit, and prepare reviewable outreach drafts.</p></div><div className="header-actions"><span className="safe">{demoMode?"PUBLIC READ-ONLY PREVIEW":"LIVE SEARCH · OUTBOUND APPROVAL REQUIRED"}</span><button className="secondary" onClick={()=>{if(!demoMode){clearToken();setLoggedIn(false)}}}>{demoMode?"Public preview":"Sign out"}</button></div></header>
 {error&&<div className="error">{error}</div>}<section className="searchbar"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search live freelance opportunities..."/><button onClick={runDiscovery} disabled={demoMode||loading||!query.trim()}>{loading?"Searching…":"Search Live Web"}</button></section>
 {discoveryResult&&<div className="notice">Discovered {discoveryResult.discovered||0} · Added {discoveryResult.created||0} · Duplicates {discoveryResult.duplicates||0} · Analyzed {discoveryResult.analyzed||0} · Qualified {discoveryResult.qualified||0}</div>}
 <div className="discovery-status"><span className="eyebrow">WORKERS</span><strong>Discovery: {worker?.discovery?.status||"unknown"}</strong><strong>Follow-ups: {worker?.followups?.status||"unknown"}</strong><span>{dashboard.last_discovery_at?"Last discovery "+new Date(dashboard.last_discovery_at).toLocaleString():"No automated discovery cycle recorded yet."}</span></div>
 <section className="metrics">{[["Opportunities",dashboard.opportunities||0],["Qualified",dashboard.qualified||0],["High Match",dashboard.high_match||0],["Proposals",dashboard.proposals||0],["Follow-ups Due",dashboard.followups_due||0]].map(([k,v])=><article className="metric" key={k}><span>{k}</span><strong>{v}</strong></article>)}</section>
 <OutreachCenter/><AcquisitionIntelligence/><AutonomousIntelligence/>{proposalWorkspaceId&&<ProposalWorkspace proposalId={proposalWorkspaceId} onClose={()=>setProposalWorkspaceId(null)}/>}
 <section className="panel due-panel"><div className="panel-head"><div><div className="eyebrow">ACTION QUEUE</div><h2>Due Follow-ups</h2></div><span className="draft">READY FOR ACTION · NOT SENT</span></div>{!dueFollowups.length?<div className="empty">No approved follow-ups are due.</div>:dueFollowups.map(x=><div key={x.id} className="due-row"><div><b>{x.lead_title||("Lead #"+x.lead)}</b><div className="muted">{new Date(x.scheduled_at).toLocaleString()} · {x.message}</div></div><span className="status">DUE</span><button className="secondary" onClick={()=>sendFollowup(x.id)} disabled={loading}>Send approved follow-up</button></div>)}</section>
 <main className="workspace"><aside className="panel pipeline"><div className="panel-head"><div><div className="eyebrow">PIPELINE</div><h2>Opportunities</h2></div><div className="filters"><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All</option><option value="new">New</option><option value="qualified">Qualified</option><option value="proposal">Proposal</option><option value="contacted">Contacted</option><option value="replied">Replied</option><option value="won">Won</option><option value="lost">Lost</option><option value="fresh-qualified">Fresh Qualified</option></select><select value={sort} onChange={e=>setSort(e.target.value)}><option value="score">Highest match</option><option value="newest">Newest</option><option value="title">Title</option></select></div></div>
 {!visible.length?<div className="empty">No opportunities yet. Search the live web to discover current leads.</div>:visible.map(lead=><button key={lead.id} className={"lead-row "+(selected?.id===lead.id?"active":"")} onClick={()=>selectLead(lead)}><div className="lead-title">{lead.title}</div><div className="muted">{lead.company||"Independent"} · {lead.source}</div><div className="muted">{lead.posted_at?"Posted "+new Date(lead.posted_at).toLocaleDateString():"Posted date unknown"}{lead.expires_at?" · Expires "+new Date(lead.expires_at).toLocaleDateString():""}</div><div className="chips"><span>{lead.status}</span>{lead.analysis?.match_score!=null&&<span>Match {lead.analysis.match_score}</span>}{(lead.technologies||[]).slice(0,3).map(t=><span key={t}>{t}</span>)}</div></button>)}{(leadPagination.count||0)>0&&<div className="pager"><button className="secondary" disabled={!leadPagination.previous||loading} onClick={()=>setLeadPage(p=>Math.max(1,p-1))}>Previous</button><span>Page {leadPage} · {leadPagination.count} total</span><button className="secondary" disabled={!leadPagination.next||loading} onClick={()=>setLeadPage(p=>p+1)}>Next</button></div>}</aside>
 <section className="panel detail">{!selected?<div className="empty large"><div><div className="empty-icon">✦</div><h3>Select an opportunity</h3><p>Inspect fit, analyze requirements, then generate a proposal draft for review.</p></div></div>:<div><div className="detail-head"><div><div className="eyebrow">{selected.lead_type}</div><h2>{selected.title}</h2><p>{selected.company||"Independent"}</p></div><span className="status">{selected.status}</span></div><div className="detail-body"><p className="description">{selected.description}</p><div className="facts"><div><span>Source</span><b>{selected.source}</b></div><div><span>Budget</span><b>{selected.budget_text||"Not stated"}</b></div><div><span>Tech</span><b>{(selected.technologies||[]).join(", ")||"Not stated"}</b></div></div>{selected.source_url&&<p><a href={selected.source_url} target="_blank" rel="noreferrer">Open source listing ↗</a></p>}<div className="actions"><button onClick={runAnalysis} disabled={demoMode||loading}>{loading?"Working…":"Analyze opportunity"}</button><button className="secondary" onClick={generateProposal} disabled={demoMode||loading||!analysis}>Generate proposal</button><select value={selected.status} onChange={e=>setStatus(e.target.value)} disabled={loading}>{["new","qualified","proposal","contacted","replied","won","lost","archived"].map(s=><option key={s} value={s}>{s}</option>)}</select></div>
 {analysis&&<div className="card"><div className="card-head"><div><div className="eyebrow">AI QUALIFICATION</div><h3>{analysis.service_match||"Needs review"}</h3></div><div className="score">{analysis.match_score}</div></div><div className="scorebar"><span style={{width:(analysis.match_score||0)+"%"}}/></div><div className="grid"><div><span>Relevant</span><b>{analysis.relevant?"Yes":"Needs review"}</b></div><div><span>Confidence</span><b>{analysis.confidence}/100</b></div></div><div className="block"><span>Requirements</span><p>{(analysis.requirements||[]).join(", ")||"None extracted"}</p></div><div className="block"><span>Pain points</span><p>{(analysis.pain_points||[]).join(" ")}</p></div><div className="block"><span>Recommended approach</span><p>{analysis.recommended_approach}</p></div><div className="block"><span>Matching projects</span><p>{(analysis.matching_projects||[]).join(" · ")||"None"}</p></div></div>}
 <div className="card"><div className="card-head"><div><div className="eyebrow">FOLLOW-UP</div><h3>Schedule reviewable follow-up</h3></div><span className="draft">DRAFT · NOT SENT</span></div><div className="actions"><input type="datetime-local" value={followupDate} onChange={e=>setFollowupDate(e.target.value)}/><input value={followupMessage} onChange={e=>setFollowupMessage(e.target.value)} placeholder="Follow-up message..."/><button onClick={createFollowup} disabled={loading||!followupDate||!followupMessage.trim()}>Schedule draft</button><button className="secondary" onClick={createSequence} disabled={loading}>Create 3-step intelligent sequence</button></div>{sequence&&<div className="notice">Sequence #{sequence.id} created. Each step remains a draft until approved.</div>}{followups.filter(f=>f.lead===selected.id).map(f=><div key={f.id} className="muted">Scheduled {new Date(f.scheduled_at).toLocaleString()} · {f.status}{f.status==="draft"&&<button onClick={()=>approveFollowup(f.id)} disabled={loading}>Approve</button>}</div>)}</div>
 <div className="card"><div className="card-head"><div><div className="eyebrow">REPLY TRACKING</div><h3>Record a client reply</h3></div><span className="draft">MANUAL · NO OUTBOUND</span></div><div className="actions"><textarea value={replyMessage} onChange={e=>setReplyMessage(e.target.value)} placeholder="Paste the client's reply here..."/><button onClick={createReply} disabled={loading||!replyMessage.trim()}>Record & analyze reply</button></div>{replyClassification&&<div className="block"><span>AI reply recommendation</span><p><b>{replyClassification.intent}</b> · {replyClassification.sentiment} · {replyClassification.urgency}</p><p>{replyClassification.recommended_action}</p><p>{replyClassification.suggested_response}</p></div>}</div>
 {proposal&&<div className="card proposal"><div className="card-head"><div><div className="eyebrow">OUTREACH DRAFT</div><h3>Review before action</h3></div><span className="draft">{proposal.medium||"delivery"} · {proposal.status==="approved"?"APPROVED · NOT SENT":"DRAFT · NOT SENT"}</span></div><pre>{proposal.message}</pre>{proposal.proposal_id&&<button className="secondary" onClick={()=>setProposalWorkspaceId(proposal.proposal_id)}>Open proposal workspace</button>}{proposal.status==="draft"&&<button onClick={approveProposal} disabled={loading}>Approve draft</button>}{proposal.status==="approved"&&proposal.medium==="email"&&<><button onClick={sendProposal} disabled={loading}>Send approved email</button><p className="muted">Sending is provider-gated and remains disabled until explicitly enabled.</p></>}{proposal.status==="approved"&&proposal.medium!=="email"&&<><a className="button-link" href={proposal.destination_url} target="_blank" rel="noreferrer">Open destination ↗</a><p className="muted">Submit the proposal on the platform, then mark it submitted in Outreach Center.</p></>}{proposal.status==="sent"&&<p className="muted">Sent through the configured outreach provider.</p>}</div>}</div></div>}</section></main></div>
}
export default App;
