# Generated by Django 5.2.17
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("leads", "0031_alter_followup_status")]

    operations = [
        migrations.AlterField(
            model_name="followup",
            name="status",
            field=models.CharField(default="draft", max_length=20),
        ),
    ]
